# Generated by Django 6.0.6 on 2026-06-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_options_property_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={},
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(choices=[('Lalpur', 'Lalpur'), ('Kanke Road', 'Kanke Road'), ('Doranda', 'Doranda'), ('Bariatu', 'Bariatu'), ('Kokar', 'Kokar'), ('Namkum', 'Namkum'), ('Argora', 'Argora / Harmu'), ('Ratu Road', 'Ratu Road')], default='Lalpur', max_length=100),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Optional: Image description', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='property_gallery/'),
        ),
    ]
